import "dotenv/config"

const FIREBASE_APIKEY = process.env.FIREBASE_APIKEY
const FIREBASE_AUTHDOMAIN = process.env.FIREBASE_AUTHDOMAIN
const FIREBASE_PROJECTID = process.env.FIREBASE_PROJECTID
const FIREBASE_STORAGEBUCKET = process.env.FIREBASE_STORAGEBUCKET
const FIREBASE_MESSAGINGSENDERID = process.env.FIREBASE_MESSAGINGSENDERID
const FIREBASE_APPID = process.env.FIREBASE_APPID
const FIREBASE_MEASUREMENTID = process.env.FIREBASE_MEASUREMENTID
const EXPO_PROJECT_ID = process.env.EXPO_PROJECT_ID


export default {
    "owner": "wearedarsh",
    extra:{
        FIREBASE_APIKEY: FIREBASE_APIKEY,
        FIREBASE_AUTHDOMAIN: FIREBASE_AUTHDOMAIN,
        FIREBASE_PROJECTID: FIREBASE_PROJECTID,
        FIREBASE_STORAGEBUCKET: FIREBASE_STORAGEBUCKET,
        FIREBASE_MESSAGINGSENDERID: FIREBASE_MESSAGINGSENDERID,
        FIREBASE_APPID: FIREBASE_APPID,
        FIREBASE_MEASUREMENTID: FIREBASE_MEASUREMENTID,
        "eas": {
            "projectId": EXPO_PROJECT_ID
        }
    }
}