import "dotenv/config"

const FIREBASE_APIKEY = process.env.FIREBASE_APIKEY
const FIREBASE_AUTHDOMAIN = process.env.FIREBASE_AUTHDOMAIN
const FIREBASE_PROJECTID = process.env.FIREBASE_PROJECTID
const FIREBASE_STORAGEBUCKET = process.env.FIREBASE_STORAGEBUCKET
const FIREBASE_MESSAGINGSENDERID = process.env.FIREBASE_MESSAGINGSENDERID
const FIREBASE_APPID = process.env.FIREBASE_APPID
const FIREBASE_MEASUREMENTID = process.env.FIREBASE_MEASUREMENTID
const SALT = process.env.SALT
const EXPO_PROJECT_ID = process.env.EXPO_PROJECT_ID
const EMAIL_HOST = process.env.EMAIL_HOST
const EMAIL_AUTH_USER = process.env.EMAIL_AUTH_USER
const EMAIL_AUTH_PASS = process.env.EMAIL_AUTH_PASS


export default {
    "owner": "wearedarsh",
    extra:{
        FIREBASE_APIKEY: FIREBASE_APIKEY,
        FIREBASE_AUTHDOMAIN: FIREBASE_AUTHDOMAIN,
        FIREBASE_PROJECTID: FIREBASE_PROJECTID,
        FIREBASE_STORAGEBUCKET: FIREBASE_STORAGEBUCKET,
        FIREBASE_MESSAGINGSENDERID: FIREBASE_MESSAGINGSENDERID,
        FIREBASE_APPID: FIREBASE_APPID,
        FIREBASE_MEASUREMENTID: FIREBASE_MEASUREMENTID,
        EMAIL_HOST: EMAIL_HOST,
        EMAIL_AUTH_USER: EMAIL_AUTH_USER,
        EMAIL_AUTH_PASS: EMAIL_AUTH_PASS,
        SALT: SALT,
        "eas": {
            "projectId": EXPO_PROJECT_ID
        }
    }
}